### PR TITLE
Add some comments on findFile

### PR DESCRIPTION
**Pull request by raxod502**
Add some comments to the code that was added in https://github.com/tachiyomiorg/UniFile/pull/2, to help future developers understand the approach and its limitations, as per the comment thread at https://github.com/tachiyomiorg/UniFile/pull/2.

DCO statement: The contribution was created in whole by [Radian LLC](https://radian.codes/), which attests its right to submit it to the project under the terms of the Apache License.

### CODE REVIEW

**Comment by FooIbar** [comment]
|||
| --- | --- |
| image | image |

https://discord.com/channels/1195734228319617024/1196111629482463422/1237165955667197953
Here it comes.
I knew some OEMs gonna have weird providers.

Seems to be a known issue on Huawei.
https://stackoverflow.com/questions/61977022/android-saf-duplicate-1-2-files-are-created-on-huawei

**Comment by raxod502** [comment]
Well then. I suppose it is best to create a conditional branch that falls back to the legacy (extremely slow) iteration behavior when on a broken device. Do you happen to know what property we can check to determine if we're running on a Huawei device? I don't own one that I could use for testing.

**Comment by FooIbar** [comment]
> Well then. I suppose it is best to create a conditional branch that falls back to the legacy (extremely slow) iteration behavior when on a broken device. Do you happen to know what property we can check to determine if we're running on a Huawei device? I don't own one that I could use for testing.

Maybe it's a specific build of EMUI thing.
I know some other users who are using Huawei as well didn't encounter this.

**Comment by raxod502** [comment]
Hmmm... maybe if we can't reliably identify the problem, we can write a test for it, so the library can create and delete a temporary file the first time it is asked to perform an operation, and determine which code-path to use based on the results. Or, perhaps it can check the URI structure to see if it matches the expected delimiter schema (seems more likely to be the problem here?).

Is there anyone in the community who has such a device that I would be able to work with to gather test data and develop an appropriate solution?

**Comment by FooIbar** [comment]
> Hmmm... maybe if we can't reliably identify the problem, we can write a test for it, so the library can create and delete a temporary file the first time it is asked to perform an operation, and determine which code-path to use based on the results. Or, perhaps it can check the URI structure to see if it matches the expected delimiter schema (seems more likely to be the problem here?).
> 
> Is there anyone in the community who has such a device that I would be able to work with to gather test data and develop an appropriate solution?

After some investigation, I think that was due to the user didn't enable "show internal storage" in the file manager and chose `Downloads` as download location.
Thankfully we don't need to do anything.

**Comment by raxod502** [comment]
Whew, good thing. I was not looking forward to remote debugging a weird filesystem implementation. But if people do end up running into issues with the change, I am happy to help with investigation and a patch.

**Pull request merged**
